name: epfl
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - expat=2.5.0
  - ffmpeg=4.3
  - fftw=3.3.9
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - h5py=3.7.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - joblib=1.1.1
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124
  - libcurand=10.3.3.141=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17
  - libevent=2.1.12
  - libffi=3.4.4
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39
  - libpq=12.15
  - libtiff=4.5.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - numexpr=2.8.4
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1w
  - packaging=22.0
  - pandas=1.3.5
  - pcre=8.45
  - pillow=9.4.0
  - pip=22.3.1
  - ply=3.11
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.7.16
  - python-dateutil=2.8.2
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - requests=2.28.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.12.2
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tornado=6.2
  - typing_extensions=4.3.0
  - ujson=5.4.0
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - calmsize==0.1.3
      - memory-profiler==0.61.0
      - opacus==1.4.0
      - opt-einsum==3.3.0
      - psutil==5.9.5
      - pybind11==2.11.1
      - seal==4.0.0
