name: epfl
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex
  - blas
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - cuda-cudart
  - cuda-cupti
  - cuda-libraries
  - cuda-nvrtc
  - cuda-nvtx
  - cuda-runtime
  - cycler
  - cyrus-sasl
  - expat
  - ffmpeg
  - fftw
  - fontconfig
  - fonttools
  - freetype
  - giflib
  - glib
  - h5py
  - hdf5
  - icu
  - idna
  - intel-openmp
  - joblib
  - jpeg
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libcublas
  - libcufft
  - libcurand
  - libcusolver
  - libcusparse
  - libdeflate
  - libevent
  - libffi
  - libiconv
  - libllvm14
  - libnpp
  - libnvjpeg
  - libpng
  - libpq
  - libtiff
  - libwebp
  - libwebp-base
  - libxml2
  - libxslt
  - lz4-c
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandas
  - pcre
  - pillow
  - pip
  - ply
  - pycparser
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - python=3.9
  - python-dateutil
  - pytorch
  - pytorch-cuda
  - pytorch-mutex
  - pytz
  - qt-main
  - qt-webengine
  - qtwebkit
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - sip
  - six
  - sqlite
  - threadpoolctl
  - tk
  - toml
  - torchaudio
  - torchvision
  - tornado
  - typing_extensions
  - ujson
  - urllib3
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
      - calmsize
      - memory-profiler
      - opacus
      - opt-einsum
      - psutil
      - pybind11
